### ISSUE TITLE
Logo sprite

### ISSUE THREAD

**Issue by calumet45** [carpoolagency/carpoolagency.github.io#1]
I didn't know where else to put this just to have it on record

```css
.stitches-cpsprite(@x: 0, @y: 0, @width: 0, @height: 0) {
    background-position: @x @y;
    width: @width;
    height: @height;
}

.cpsprite {
    background-image: url('http://carpoolagency.github.io/carpool/img/svg_icons/carpool_logo_white.svg');    background-repeat: no-repeat;
        display: inline-block;
    background-size: 200px 60px;
  

    &.cpsprite-carpool {
        .stitches-cpsprite(0, 0, 158px, 53px);
      transition:.62s all ease;
      transform-origin: left;
       .shrink & {
        transform:scale(0);
        
      } 
    }

    &.cpsprite-carpool-car {
        .stitches-cpsprite(-158px, 0, 50px, 55px);
      transition:.6s all ease;
      .shrink & {
        transform: translateX(-147px) scale(1.5);
      }
    }
}
.back {background-color:black;}
```
